
package com.ionetwork.ws.in;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SMSPortInDelegate", targetNamespace = "http://www.ionetwork.com/")
public interface SMSPortInDelegate {
	
	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendMessage", targetNamespace = "http://www.ionetwork.com/", className = "com.ionetwork.ws.in.SendMessage")
	@ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://www.ionetwork.com/", className = "com.ionetwork.ws.in.SendMessageResponse")
	public int sendMessage(@WebParam(name = "arg0", targetNamespace = "") String arg0, @WebParam(name = "arg1", targetNamespace = "") String arg1, @WebParam(name = "arg2", targetNamespace = "") String arg2, @WebParam(name = "arg3", targetNamespace = "") String arg3);
	
}
